<?php 


/**
 * Implements hook_menu().
 */
function robinsonmod_menu() {
  $base = array(
    'type' => MENU_CALLBACK,
    'file' => 'robinsonmod.pages.inc',
  );

  $items['ajax/robinson/thema'] = $base + array(
    'title' => 'ajax thema',
    'page callback' => 'robinsonmod_ajax_thema',
    'page arguments' => array(),
    'access callback' => true,
    // 'access arguments' => array(''),
  );

  $items['ajax/robinson/voisin'] = $base + array(
    'title' => 'ajax voisin',
    'page callback' => 'robinsonmod_ajax_voisin',
    'page arguments' => array(),
    'access callback' => true,
    // 'access arguments' => array(''),
  );

  return $items;
}

/**
 * Implements hook_entity_info_alter().
 */
function robinsonmod_entity_info_alter(&$entity_info) {
  $base  = array('custom settings' => TRUE);

  $entity_info['node']['view modes']['stream'] = $base + array(
    'label' => t('Stream')
  );
  $entity_info['node']['view modes']['voisin_atmosphere_audio'] = $base + array(
    'label' => t('Voisin Atmosphere audio')
  );
  $entity_info['node']['view modes']['voisin_atmosphere_video'] = $base + array(
    'label' => t('Voisin Atmosphere video')
  );
  $entity_info['node']['view modes']['voisin_atmosphere_image'] = $base + array(
    'label' => t('Voisin Atmosphere image')
  );
  $entity_info['node']['view modes']['voisin_discursif'] = $base + array(
    'label' => t('Voisin Discursif (son)')
  );
  $entity_info['node']['view modes']['voisin_contrib_txt'] = $base + array(
    'label' => t('Voisin Contribution text')
  );
  $entity_info['node']['view modes']['voisin_contrib_video'] = $base + array(
    'label' => t('Voisin Contribution video')
  );
  $entity_info['node']['view modes']['voisin_contrib_audio'] = $base + array(
    'label' => t('Voisin Contribution audio')
  );
  $entity_info['node']['view modes']['voisin_contrib_image'] = $base + array(
    'label' => t('Voisin Contribution image')
  );
}

/**
 * Implements hook_video_embed_field_handlers_alter().
 */
function robinsonmod_video_embed_field_handlers_alter(&$handlers) {
  $handlers['vimeo']['function'] = 'robinsonmod_handle_vimeo';
}

/**
 * Wrapper function to allow forcing API to be enabled for Vimeo videos.
 */
function robinsonmod_handle_vimeo($url, $settings) {
  // dsm($settings, 'settings');
  $settings['api'] = 1;
  return video_embed_field_handle_vimeo($url, $settings);
}
